urls:
  driverLocations:
    path: "/drivers/:id/locations"
    method: "PATCH"
    nsq:
      nsqLookupdAddress: ":4161"
      nsqdAddress: ":4150"
      topic: "locations"
      maxInFlight: 25
      channel: "store_location"
      handlerConcurrency: 4
  zombieDriver:
    path: "/drivers/:id"
    method: "GET"
    http:
      host: "zombie_driver"
servers:
  internal:
    address: "localhost"
    port: "8082"
  external:
    address: "localhost"
    port: "8081"